<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="minion_usv_hydro_model" params="namespace">
    <!-- List of hydrodynamic models this robot's links -->
    <link name="${namespace}/base_link">
      <!-- This flag will make the link neutrally buoyant -->
      <neutrally_buoyant>0</neutrally_buoyant>
      <!-- Link's volume -->
      <volume>${volume}</volume>
      <!-- Link's bounding box, it is used to recalculate the immersed
        volume when close to the surface.
        This is a workaround the invalid bounding box given by Gazebo-->
      <box>
        <width>${x_size}</width>
        <length>${y_size}</length>
        <height>${z_size/4}</height>
      </box>
      <!-- <cylinder>
        <radius>${x_size}</radius>
        <length>${0.05}</length>
      </cylinder> -->
      <!-- Center of buoyancy -->
      <center_of_buoyancy>${cob}</center_of_buoyancy>

      <!-- Fossen's equation of motion for underwater vehicles
      Reference:
          [1] Fossen, Thor I. Handbook of marine craft hydrodynamics and motion
          control. John Wiley & Sons, 2011.
     -->
      <hydrodynamic_model>
          <type>fossen</type>
          <!-- Added mass: see p.28 in Berg2012 -->
          <added_mass>
            0.6321  0      0      0      0       0
            0       2.1106 0      0      0       0
            0       0      2.1106 0      0       0
            0       0      0      0      0       0
            0       0      0      0      0       0
            0       0      0      0      0       0
          </added_mass>
          <!-- 0       0      0      0      0       0
          0       0      0      0      0       0
          0       0      0      0      0       0
          0       0      0      0      0       0
          0       0      0      0      0       0
          0       0      0      0      0       0 -->
          <!--
            The linear damping coefficients can be provided as a diagonal (6 elements)
            or a full matrix (36 coefficients), like the added-mass coefficients above
            Linear damping: see p.31 in Berg2012
          -->
          <linear_damping>
            -0.5 -0.5 -0.5 -0.1 -0.1 -0.1  <!--  0 0 0 0 0 0-->
          </linear_damping>
          <!--
            The linear damping coefficients proportional to the forward speed
            can be provided as a diagonal (6 elements) or a full matrix (36 coefficients),
            like the added-mass coefficients above.
            This matrix is mostly useful for slender bodies (e.g. AUVs with torpedo shape)
          -->
          <!-- <linear_damping_forward_speed>
            0 0 0 0 0 0
          </linear_damping_forward_speed> -->
          <!--
            The quadratic damping coefficients can be provided as a diagonal (6 elements)
            or a full matrix (36 coefficients), like the added-mass coefficients above
            Non-linear damping: see p.30 in Berg2012
          -->
          <quadratic_damping>
             -3.0 -3.0 -3.0 -0.5 -0.5 -0.5
          </quadratic_damping>

          <!--
            In case you want to model a simple surface vessel, you can use the
            implementation of linear (small angle) theory for boxed shaped vessels
            by providing the following parameters. If you omit the area of the
            water level plane area, it will be calculated from the bounding box
            parameters. Uncomment the lines below in case you are simulating a
            surface vessel.
            For more details on these parameters and the computation of buoyancy
            for vessels using this theory, check:
              [1] Lecture Notes  TTK 4190 Guidance and Control of Vehicles (T. I. Fossen)
                  http://www.fossen.biz/wiley/Ch4.pdf
              [2] Fossen, Thor I. Handbook of marine craft hydrodynamics and motion
                  control. John Wiley & Sons, 2011.
          -->

          <!-- <metacentric_width>0.401</metacentric_width>
          <metacentric_length>0.401</metacentric_length> -->
          <!-- <water_level_plane_area>0.12</water_level_plane_area> -->

      </hydrodynamic_model>
    </link>
  </xacro:macro>
</robot>
